# Generated by Django 3.0.7 on 2023-07-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0002_auto_20230715_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'ADMIN'), ('2', 'STAFF'), ('3', 'STUDENT')], default='1', max_length=200),
        ),
    ]
