# Generated by Django 3.0.7 on 2023-07-20 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0013_auto_20230720_1343'),
    ]

    operations = [
 migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'ADMIN'), ('2', 'STAFF'), ('3', 'STUDENT')], default=3, max_length=200),
        ),

    ]
