# Generated by Django 3.0.7 on 2023-07-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0014_auto_20230720_1357'),
    ]

    operations = [
       
    ]
