# Generated by Django 3.0.7 on 2023-07-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0019_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneteamapp.Staff'),
        ),
    ]
