# Generated by Django 3.0.7 on 2023-07-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0021_conferncehall_laptop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfernceHall',
            new_name='Hall',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='hall_name',
            new_name='hallname',
        ),
    ]
