# Generated by Django 3.0.7 on 2023-07-24 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0022_auto_20230724_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
        migrations.AddField(
            model_name='batch',
            name='batchname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='hall_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oneteamapp.Hall'),
        ),
        migrations.AddField(
            model_name='batch',
            name='laptop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oneteamapp.Laptop'),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='staff_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oneteamapp.Staff'),
        ),
    ]
