# Generated by Django 3.0.7 on 2023-07-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0023_auto_20230724_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='stud_name',
            field=models.ManyToManyField(blank=True, to='oneteamapp.Student'),
        ),
    ]
