# Generated by Django 3.0.7 on 2023-07-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0024_batch_stud_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='stud_name',
        ),
        migrations.AddField(
            model_name='batch',
            name='stud_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='oneteamapp.Student'),
        ),
    ]
