# Generated by Django 3.0.7 on 2023-07-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0025_auto_20230724_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='stud_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oneteamapp.Student'),
        ),
    ]
