# Generated by Django 3.0.7 on 2023-07-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0026_auto_20230724_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='stud_name',
            new_name='admin_id',
        ),
    ]
