# Generated by Django 3.0.7 on 2023-07-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0027_auto_20230724_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='admin_id',
        ),
    ]
