# Generated by Django 3.0.7 on 2023-07-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0028_remove_batch_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
