# Generated by Django 3.0.7 on 2023-07-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0029_auto_20230724_1735'),
    ]

    operations = [
         migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateField(),
        ),
    ]
