# Generated by Django 3.0.7 on 2023-07-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0032_auto_20230724_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batch',
            new_name='Batches',
        ),
    ]
