# Generated by Django 3.0.7 on 2023-07-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0033_auto_20230724_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
