# Generated by Django 3.0.7 on 2023-07-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneteamapp', '0036_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=10)),
                ('marks_math', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marks_science', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marks_english', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
